matrix:
  include:
    - language: java
      jdk: openjdk11
      before_script:
        - cd classads
      script:
        - mvn clean package
    - language: node_js
      before_script:
        - cd frontend
      script:
        - npm run build
